// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHb9hT8dCK2ZgZLqzRvV9eCjC1KvtXewM',
    appId: '1:367421595104:web:22b49ff566cecfd0091f85',
    messagingSenderId: '367421595104',
    projectId: 'world-market-9774c',
    authDomain: 'world-market-9774c.firebaseapp.com',
    storageBucket: 'world-market-9774c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDujaPOxP5pEFDwK2pFiDZ0Ch6oJ-BQOqc',
    appId: '1:367421595104:android:e48a076b5a6fbb3f091f85',
    messagingSenderId: '367421595104',
    projectId: 'world-market-9774c',
    storageBucket: 'world-market-9774c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm5V7Iypvh2VeMnpdj4B8b8p6HoWfU-gA',
    appId: '1:367421595104:ios:cbc2b47f805181e2091f85',
    messagingSenderId: '367421595104',
    projectId: 'world-market-9774c',
    storageBucket: 'world-market-9774c.firebasestorage.app',
    iosBundleId: 'com.example.marketWorld',
  );
}
